### ISSUE TITLE
Code style suggestion

### ISSUE THREAD

**Issue by Xett** [ascedmor/slayTheHero#2]
Ayy bro, not to be a dick, but here is the coding style conventions for python.

https://www.python.org/dev/peps/pep-0008

Class names should normally use the CapWords convention. They don't need the () after the class name either.

Your class method names are already on point, and so are your variable names.

**Comment by ascedmor** [comment]
Awesome, appreciate the heads up, I will go through and fix up the class names today if I get time

**Comment by Xett** [comment]
yeet
